# Generated by Django 4.1 on 2022-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('accepted', 'accepted')], default='applied', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images')),
                ('company_name', models.CharField(max_length=120)),
                ('bio', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('services', models.CharField(choices=[('Software services', 'Software services'), ('Training services', 'Training services'), ('Consulting services', 'Consulting services'), ('Security services', 'Security services'), ('Marketing services', 'Marketing services')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.TextField()),
                ('role', models.CharField(max_length=120)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
