# Generated by Django 4.1 on 2022-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('qualification', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(default=17)),
                ('skills', models.CharField(max_length=120, null=True)),
                ('cv', models.FileField(null=True, upload_to='cvs')),
            ],
        ),
    ]
